name: rental_notifications_bot
description: A sample command-line application.
version: 1.0.0
# dart pub run build_runner build --delete-conflicting-outputs

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.8
